### ISSUE TITLE
require local files in script

### ISSUE THREAD

**Issue by bebbi** [weixu365/serverless-scriptable-plugin#16]
If you require directory-local dependencies inside a script called by `serverless-scriptable-plugin` and use relative imports:

    const myLib = require('./myLib')

it will try to resolve './myLib' against a base path of `<PROJECT_ROOT>/node_modules/serverless-scriptable-plugin/index.js`

A workaround is

    const myLib = require(`${__dirname}/myLib`)

**Comment by weixu365** [comment]
Thanks for reporting the issue, fixed in version 0.8.0
