### ISSUE TITLE
List of hooks

### ISSUE THREAD

**Issue by bfelbo** [weixu365/serverless-scriptable-plugin#38]
This looks great. However, where can I find a list of hooks to attach to?

**Comment by bfelbo** [comment]
I tried adding this, but nothing prints.

serverless.yml
```
plugins:
  - serverless-scriptable-plugin

custom:
  scriptHooks:
    - before:package:initialize: npm run pre-packaging
    - after:package:finalize: npm run post-packaging
```

package.json
```
{
  "scripts": {
    "pre-packaging": "sh scripts/pre_packaging.sh",
    "post-packaging": "sh scripts/post_packaging.sh",
  },
}
```

scripts/pre_packaging.sh
```
#!/bin/sh
echo "Hello World"
```

scripts/post_packaging.sh
```
#!/bin/sh
echo "Hello World"
```

**Comment by weixu365** [comment]
1. The hooks are different to providers, here's a reference of AWS hooks:
https://gist.github.com/HyperBrain/50d38027a8f57778d5b0f135d80ea406#file-lifecycle-cheat-sheet-md

2. The hook names you added to the serverless.yml are correct, but need a little bit changes (remove `-` before hook name):
```
plugins:
  - serverless-scriptable-plugin

custom:
  scriptHooks:
    before:package:initialize: npm run pre-packaging
    after:package:finalize: npm run post-packaging
```

**Comment by bfelbo** [comment]
Thank you for the help!

As someone new to serverless, the impact of these tiny differences in the yaml is quite astonishing..
