### ISSUE TITLE
Is there a way to pass SLS outputs or SLS cloudformation Refs into the custom script as args?

### ISSUE THREAD

**Issue by iDVB** [weixu365/serverless-scriptable-plugin#7]
Would love if there was a way to pass into the custom script either SLS outputs or SLS cloudformation Refs. This way, you could act on dynamic resources that have been created.

**Comment by weixu365** [comment]
Hi @iDVB , could you describe what's the scenario for this requirement?

This is not so straightforward because the SLS outputs only available after deployment which makes the scriptable plugin has to understand the deployment lifecycle.

There's a different approach to make it work: you can call sls command to get resources/outputs and pass it to your script. 

More concerns/suggestions/discussions are welcome.

**Comment by iDVB** [comment]
@weixu365 sure.... our particular scenario is that CloudFormation doesn't currently support ElasticTranscoder. However, our stack requires this piece. 

Would be great to just shim a small `deploy` and `remove` js scripts that create and destroy these resources and then just use `serverless-scriptable-plugin` to attach those scripts to the native `deploy` and `remove`. 

In the case of `deploy` the OUTPUT of the serverless.yml needs to be the INPUT for the above script, as the script needs to know buckets etc that are created in the YML.

**Comment by weixu365** [comment]
Hi @iDVB , I checked the serverless code and found that I can't get the outputs and resources. The main reason is there are multiple providers in serverless, e.g. aws, google cloud, azure ..., and output/resources is a concept of AWS ( this is my assumption ), as a generic plugin, it doesn't know how to get the resources.

But as a workaround, you can get it from another serverless command: serverless info, or check the CloudFormation stack by the script itself.

In this case, I can pass the service name and stage name to scripts. If your script is written in node.js, then you can get the service name and stage name from serverless object, e.g.
```
console.log(serverless.service.service)
console.log(serverless.processedInput.options)
```

If it's written in other language, I can create a pull request to pass service-name and command line options as an environment variable, like
```
process.env.SLS_SERVICE_NAME = 'test-service'
process.env.SLS_CLI_OPTIONS = '{ stage: 'dev', region: 'us-east-1' }'
or 
process.env.SLS_CLI_OPTION_STAGE = 'dev'
process.env.SLS_CLI_OPTION_REGION = 'us-east-1'
```

then you can get the outputs/resources from the aws stack which is ${serviceName}-${stage}
Will this solve your problem?

**Comment by iDVB** [comment]
I think so. Thanks for the work around. Let me give something a try.

**Comment by weixu365** [comment]
Let me know if you want to add the change. Or you can also just put the command in one script file
```
deploy() {
  serverless deploy
  deploy transcoder
}
```

You get everything almost same. Both of them are not transactional, so if the second one failed, it doesn't rollback the first one.

For the ideal solution, you have to wait until Cloudformation support transcoder.

**Comment by weixu365** [comment]
It's better to use other work arounds, so closed this issue.
