### ISSUE TITLE
Changing the content to template file before deployment

### ISSUE THREAD

**Issue by ShadabFaiz** [weixu365/serverless-scriptable-plugin#75]
This is more of a question than a bug.
I'm using AWS app-sync with Serverless. Can we change the content of template file before the package is generated for deployment. Cahnge should not be in the original file but in the package generated only.
For Example: I want to use some code from a json file in template file. I'll add a placeholder for it. Druing deployment, before pacakage is generated, I want the placeholder to be replaced with the actual code in the generated file.

**Comment by weixu365** [comment]
I think there are two options that could achieve this.
1. Customize the `package` behavior, which means you do the whole package work and decide what would be packaged and how. 
2. Customize the `after:package` behavior, which means you could change the file after the package file generated (unzip, change, and zip)
 
Would any of these two work for you?

**Comment by weixu365** [comment]
Any updates on this, if not, I will close the issue @ShadabFaiz
