### ISSUE TITLE
PR suggestion: command

### ISSUE THREAD

**Issue by bebbi** [weixu365/serverless-scriptable-plugin#76]
@weixu365 I've modified your plugin to support custom commands instead of hooks.

commands executed via serverless have the big advantage of allowing to feed the `serverless` variable including environment to scripts, e.g. for running migrations etc.

Would you welcome a PR of "command" functionality back into your lib?

**Comment by weixu365** [comment]
PRs are welcome, could you please create a PR first so I can understand the purpose?

It would be awesome if you can describe the use case and how to use the tool to help.

**Comment by bebbi** [comment]
> It would be awesome if you can describe the use case and how to use the tool to help.

Let's try to agree on whether your lib welcomes that functionality before I create the PR.

Use-case:
In a multi-stage environment I need to run a) a database migration, or b) a custom data extraction script.

Looking at your plugin, these scripts have in common that they need access to the serverless variable in order to extract env variables. These could be direct env variables, or stage-specific variables directing client code to pull SSM values to pull, etc.

Solution:
There's already serverless-plugin-scripts for this but unlike your lib it doesn't give access to the `serverless` object.

Proposal:

Adding a second namespace in the serverless file, e.g. `scriptCommands`, merging this logic:

```
class Plugin {
  constructor(serverless, options) {
    this.serverless = serverless
  
    // etc per existing plugin ...

    const scriptCommands = this.getScriptCommands()

    this.hooks = {}
    this.commands = {}

    Object.keys(scriptCommands).forEach((name) => {
      this.hooks[`${name}:${name}`] = this.runScript(scriptCommands[name])

      this.commands[name] = {
        usage: `Run ${scriptCommands[name]}`,
        lifecycleEvents: [name],
      }
    }, this)
  }

  getScriptCommands() {
    const { custom } = this.serverless.service
    return custom && custom.scriptCommands ? custom.scriptCommands : {}
  }

  // etc...
}
```

**Comment by weixu365** [comment]
Overall that looks great idea, just two more detailed questions

1. Could you please also propose an example of the config file? the custom namespace `scriptCommands` looks good to me.
Am I correct that the config would be something that looks like this:
```yaml
scriptCommands:
   migrate: scripts/migrate.js
   extract: python extract.py
```

2. How do we run the custom command? I'm not familiar with this, are we able to run by `serverless migrate`?

**Comment by bebbi** [comment]
Yes to both. Also, `serverless help` output:

```
migrate ................ Run scripts/migrate
extract ................ Run python extract.py
```

(I did it only for node scripts but should be straightforward to do for both as the lib already has that logic.)

**Comment by weixu365** [comment]
That's really cool, thanks for the proposal, and the PR is welcome.

**Comment by bebbi** [comment]
I assume keys like `showStdoutOutput` should be global (across both namespaces `scriptHooks` and `scriptCommands` ?
The clean solution (with or without second namespace) might be a breaking change with global namespace:

```
custom:
  scriptable:
    showStdoutOutput: true
    ...
    hooks:
        before:package:createDeploymentArtifacts: npm run build
    commands:
        sayHello: echo hello
```

What do you think?

**Comment by weixu365** [comment]
I think the new structure is good. But from the code level, we need to make it backward compatible, so
1. Keep the current logic, so that everything except `showXXX`, `hooks`, and `commands` under `scriptable` are hooks
2. Add support of `hooks` and `commands`, and it could have a higher priority

so the following config should also work:
```
custom:
  scriptable:
    showStdoutOutput: true
    ...
    before:package:createDeploymentArtifacts: npm run build-backward-compatible

    hooks:
        before:package:createDeploymentArtifacts: npm run build-hooks
    commands:
        sayHello: echo hello
```

The actual hook of `before:package:createDeploymentArtifacts` would be `npm run build-hooks`

**Comment by bebbi** [comment]
How about the new top-level name `scriptable` not being backwards compatible with `scriptHooks`?
(`scriptHooks` does seem confusing if we add commands under it.)

**Comment by bebbi** [comment]
We could also check for `scriptHooks` top level name and throw an error with migration instructions

**Comment by weixu365** [comment]
Oops, I didn't notice that has changed, how about keep `scriptHooks` for backward compatible, and add `scriptable` with exact structure as you suggested and has a higher priority (overwrite `scriptHooks` if conflicted). 

So that the current users are not affected, and the new features also could be added.

We could also change the doc to use `scriptable`, eventually only `scriptable` will be used.

**Comment by bebbi** [comment]
(see PR about tests, and also the docs need update)

**Comment by bebbi** [comment]
@weixu365 have you found out about the failing tests? Let me know how it goes. Would it be reasonable that you adjust the tests and If you have a commit, I add that on top of the PR and then adjust docs in an additional commit?

**Comment by bebbi** [comment]
Btw, you may have seen in the PR that to stay minimally invasive, I always use `scriptHooks` if it exists (irrespective of the `scriptable` key existence) but raise the migration warning.

**Comment by weixu365** [comment]
I have merged the PR into a branch, added a few tests, and changed docs. The PR is here: https://github.com/weixu365/serverless-scriptable-plugin/pull/78, working on fixing styles now.

**Comment by weixu365** [comment]
I have changed the logic of merging configs to the following:
- showXXX, read the first value from `scriptable.showXXX`, `hookScripts.showXXX` in order
- hooks, merge `scriptable.hooks` and any existing hooks under `hookScripts`,  `scriptable.hooks` would have a higher priority if the name conflicts

Basically, `scriptable.xxx` always has a higher priority.

**Comment by weixu365** [comment]
Could you please review/test the PR to make sure it would work in your scenario? https://github.com/weixu365/serverless-scriptable-plugin/pull/78

**Comment by bebbi** [comment]
Thanks for your help 🙏, that's super cool. I did a PR review for some minor points. I have tested the code in our project (no `scriptHooks`, only `scriptable` and it works as expected. I did a manual review for the (new) logic of priority and all looks fine.

**Comment by bebbi** [comment]
..I just thought about a super minor inconsistency, will add that to the review..

**Comment by bebbi** [comment]
OK I made my final review comment on `this.isFalse`.

There's a super minor inconsistency in the current PR where `this.first()` would essentially convert `showXXX: null` serverless definitions into `showXXX: undefined`. Therefore I suggest to not treat `null` as `false` in `isFalse()` which is reasonable anyway. But it is a breaking change for someone who comes up with the idea of setting `false` as `null` (a very minor chance for someone to do that indeed..)

**Comment by bebbi** [comment]
The alternative is that you exclude `null` as a skip value in `this.first()`: `return vals.findIndex(val => typeof val !== 'undefined')`

**Comment by weixu365** [comment]
This is a great catch. I would assume all these values are false: `false`, `null`, and `undefined`.

**Comment by bebbi** [comment]
`undefined` should be `true` right? Because that's the default which remains if the option is undefined.

**Comment by weixu365** [comment]
Yes, you are correct, the value of `false or 0` would be false, `undefined and null` would be true:
```
    expect(scriptable.isFalse(undefined)).equal(false);
    expect(scriptable.isFalse(null)).equal(false);
    expect(scriptable.isFalse(true)).equal(false);
    expect(scriptable.isFalse('0')).equal(false);
    expect(scriptable.isFalse(1)).equal(false);

    expect(scriptable.isFalse(false)).equal(true);
    expect(scriptable.isFalse(0)).equal(true);
```

**Comment by bebbi** [comment]
Yes exactly, and AFAIK in the old code null was false.
options:
- maintain old code -> change `isFirst` per above
- correct the code for reading null as true: -> change `isFalse()` to `!= null`

**Comment by weixu365** [comment]
I think it should be acceptable for either behavior, and the `null` value should not be encouraged anyway, so I would assume `null` would have the default behavior which is `showing XXX`

**Comment by weixu365** [comment]
Merged the PR, the new version will be released in a couple of minutes
