### ISSUE TITLE
Can't seem to get this to fire before another plugin...

### ISSUE THREAD

**Issue by iDVB** [weixu365/serverless-scriptable-plugin#9]
I'm using the [serverless-stack-output](https://github.com/sbstjn/serverless-stack-output/blob/master/src/plugin.ts#L15) plugin which is using `after:deploy:deploy` and I still can't get `serverless-scriptable-plugin` to fire AFTER it, whether I use `after:deploy:finalize` or `after:deploy:deploy`

**Comment by weixu365** [comment]
What's your serverless configuration? 

Does serverless-scriptable-plugin able to fire if you have disable other plugins?

**Comment by iDVB** [comment]
@weixu365 it "fires" now just fine. 
It just fires **before** the other plugin, when I want it to fire **after**.

The part that confuses me is that the other plugin uses [`after:deploy:deploy`](https://github.com/sbstjn/serverless-stack-output/blob/master/src/plugin.ts#L15)

And I've tried configuring `serverless-scriptable-plugin` to both `after:deploy:deploy` and `after:deploy:finalize` and still can't get it to fire **after**.

**Comment by weixu365** [comment]
Did you tried to change the plugin order in serverless config file?

**Comment by iDVB** [comment]
Yes, `serverless-scriptable-plugin` is the very last plugin in that list.
```
plugins:
  - serverless-lambda-version
  - serverless-stack-output
  - serverless-webpack
  - serverless-scriptable-plugin
```

**Comment by weixu365** [comment]
I wrote a test service to verify the behaviour, and found that the execute order is based on plugins order in serverless.yml file

The problem you got is different one, I think it should be a bug of serverless-stack-output. serverless-stack-output is using promise to get the stack output but **DID NOT** return the promise object which causes:
- Start to execute serverless-stack-output
- Start to execute serverless-scriptable-plugin
- Finished executing serverless-stack-output

It's simple to fix this issue in serverless-stack-output, just return the promise object in 'process' method. I think you can create an issue in that repo

**Comment by weixu365** [comment]
Here's the output with return in serverless-stack-output:

```
start to get stack output
Serverless: Stack Output saved to file: ./stack.yaml
running scripts in scriptable plugin
Running javascript file: test.js
```

and here's the output without return in serverless-stack-output:

```
start to get stack output
running scripts in scriptable plugin
Running javascript file: test.js
Serverless: Removing old service versions...
Serverless: Stack Output saved to file: ./stack.yaml
```

**Comment by iDVB** [comment]
@weixu365 Thanks so much for diving deep into this! 
I already have a PR into serverless-stack-output. I'll just add this fix in as well.

Cheers,
D
